base_clearance_fee: 30000        # Customs clearance fee (RUB)
base_util_fee: 20000            # Base utilization fee

# Unified Tariff (ETC) values
etc_min_euro_per_cc: 15.0       # Minimum 15 EUR/cc
etc_euro_per_cc: 1.5            # Gasoline: 1.5 EUR/cc
etc_euro_per_cc_diesel: 2.0     # Diesel: 2.0 EUR/cc
etc_util_coeff_base: 0.26       # Base utilization coefficient for ETC

# ETC additional charges
offroad_duty_extra_percent: 0.1  # +10% duty for offroad vehicles
diesel_util_extra: 0.1           # +0.1 utilization coefficient for diesel
offroad_util_extra: 0.05         # +0.05 utilization coefficient for offroad vehicles

# Comprehensive Payment (CTP) values
ctp_base_duty_percent: 0.15     # Duty percentage for gasoline vehicles
ctp_base_duty_percent_diesel: 0.16  # Duty percentage for diesel vehicles
ctp_excise_per_hp_benzin: 912   # Excise per horsepower for gasoline
ctp_excise_per_hp_diesel: 1000  # Excise per horsepower for diesel
offroad_excise_extra: 0.1       # +10% excise for offroad vehicles

vat_percent: 0.20               # VAT rate
ctp_util_coeff_base: 15.03      # Base utilization coefficient for CTP
